#!/bin/bash
set -e

# Build, and deploy latest version of Slangbrain to the live server

server="fbot.slangbrain.com"
server_bin="/home/jorin/bin/slangbrain"

cd $GOPATH/src/github.com/jorinvo/slangbrain

echo - building binary
GOOS=linux go build -a -ldflags "-s -w  -X main.version=$(git log --format="%H" -n 1)" -o dist/slangbrain

echo - moving old binary
ssh $server mv $server_bin /tmp/slangbrain-$(date +%s)

echo - uploading to server
scp dist/slangbrain $server:$server_bin

echo - restarting service
ssh -t $server "sh -c 'sudo systemctl restart slangbrain && sudo journalctl -fu slangbrain'"

echo - all good
