#!/bin/bash
set -e

# Build, and deploy latest version of Slangbrain to the live server.


cd $GOPATH/src/github.com/jorinvo/slangbrain

echo - building binary
GOOS=linux go build -a -ldflags "-s -w  -X main.version=$(git log --format="%H" -n 1)" -o dist/slangbrain

echo - moving old binary
ssh fbot.slangbrain.com mv /home/jorin/bin/slangbrain /tmp/slangbrain-$(date +%s)

echo - uploading to server
scp dist/slangbrain fbot.slangbrain.com:/home/jorin/bin/slangbrain

echo - restarting service
ssh -t fbot.slangbrain.com sudo systemctl reload slangbrain

echo - all good
