#!/bin/bash
set -e

server="stat.slangbrain.com"
bin_name="slangbrain-stat"
server_bin="/home/jorin/bin/$bin_name"


echo - building $bin_name
GOOS=linux go build -a -ldflags "-s -w" -o dist/$bin_name ./cmd/$bin_name/main.go

echo - moving old binary on $server
ssh $server mv $server_bin /tmp/$bin_name-$(date +%s)

echo - uploading $bin_name to $server
scp dist/$bin_name $server:$server_bin

echo - all good
