#!/bin/bash
set -e

# Apply most recent migration

server="fbot.slangbrain.com"
server_db="${server}:/home/jorin/slangbrain.db"
migration="$(ls -1 migrations | tail -n1)"
migration_file="./migrations/${migration}/main.go"
num="$(echo "$migration" | cut -d_ -f1)"
before_db="backups/${num}-before.db"
after_db="backups/${num}-after.db"

mkdir -p backups

echo - using migration $migration

echo - checking for errors
errcheck $migration_file

echo - stopping service
ssh -t $server sudo systemctl stop slangbrain

echo - downloading db
scp $server_db $before_db
cp $before_db $after_db

echo - running migration
go run $migration_file $after_db
sleep 2

echo - uploading db
scp $after_db $server_db

echo - deploying latest version
./deploy
