#!/bin/bash
set -e

go run main.go \
  -db 'dev.db' \
  -verify 'SmhklHbrVi4MInnC8Fih58TBTIc$jeXTadn%bChS' \
  -token 'EAAEMXBS5vNoBAB4NbuAYJp1FhDN50UNcoFRtME4phWQEGdV3ezUUkZCVS6B1Q2vQHFPc4TUZBdMTwEWjkwzfFNR2WR5cYDxjXZCZCWKUgAlZBewOGKZB1Un2gSbaBKV2L4bgn7vR5ZC83Lo7kd53WZAimctkkwRzBmzA1UYRvR0sgQZDZD' \
  $1

