package translate

// Msg contains all messages ever send to a user.
type Msg struct {
	// Greeting is currently limited to 160 chars
	Greeting,
	Menu,
	Help,
	Idle,
	Add,
	Welcome1,
	Welcome2,
	Welcome3,
	Welcome4,
	WelcomeReferral,
	Error,
	ExplanationMissing,
	PhraseMissing,
	StudyDone,
	StudyCorrect,
	StudyWrong,
	StudyEmpty,
	StudyQuestion,
	ExplanationExists,
	AddDone,
	AddNext,
	StudyNotification,
	AskToSubscribe,
	Subscribed,
	ConfirmUnsubscribe,
	DenySubscribe,
	Feedback,
	FeedbackDone,
	ImportHelp1,
	ImportHelp2,
	ImportPrompt,
	ImportPromptIgnore,
	ImportNone,
	ImportConfirm,
	ImportCancel,
	ImportEmpty,
	ImportErrParse,
	ImportErrCols,
	AnHour,
	Hours,
	AMinute,
	Minutes,
	And string
}
